### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by vrde** [society-systems/postcoronialism#1]
# Problem

This project is free and open source software, but we still don't know yet which license to use.

# Solution

A good website to help us choosing a license is [choosealicense.com](https://choosealicense.com/). The core question is: *do we want to allow others to make and distribute closed source versions of this project?*

**Comment by vrde** [comment]
In my opinion we should encourage people to share their improvements back to the open source community, that's why I suggest to use [GNU Affero General Public License v3.0](https://choosealicense.com/licenses/agpl-3.0/).

**Comment by societyoffalsewitnesses** [comment]
Cool, I agree with using the GNU Affero General Public License v3.0
